### ISSUE TITLE
New Feature: Graph of word counts

### ISSUE THREAD

**Issue by raguay** [markwk/alfred-workflow-wordcounterapp#2]
It would be nice to be able to create and see a graph of the word counts. One for the current week, current month, and any random month. I can see where that would be very useful.

**Comment by markwk** [comment]
@raguay agreed. 

I added a small helper python script `report.py` that generates a png file with a chart of previous days. You just need to pass the number of days and target directory. I've updated the README with the how to. 

My guess is that you are looking for something that would be displayed in alfred. Unfortunately I'm not quite sure how to do that. If you have an example of another alfred workflow with an embedded chart or an idea on the approach, I'd be open to adding this. 

Thanks!

**Comment by raguay** [comment]
External is fine. But, this should be made into an Alfred launched item.

**Comment by markwk** [comment]
@raguay out of curiosity, did you test it as is? 

It makes sense to have it as an alfred launched item. Will see what's needed make it next time I tinker on it. Otherwise, feel free to tweak on your end since it probably won't take much to accomplish it really.

**Comment by raguay** [comment]
Actually, I was going to right after I wrote you, but I got sidetracked. I
just now did and all I'm getting is:

```
report.py:35: DeprecationWarning: The readPlist function is deprecated, use
load() instead
  data = plistlib.readPlist(records)
report.py:64: DeprecationWarning: This method will be removed in a future
version of Python. Use 'locale.format_string()' instead.
  return locale.format("%d", total, grouping=True)
Traceback (most recent call last):
  File "report.py", line 95, in <module>
    word_data_report(arg1, arg2)
  File "report.py", line 80, in word_data_report
    plt.title(str(dates[0])+' to '+str(dates[6]) + '\n Writing Typing Word
Count: ' + str(dates_total))
IndexError: list index out of range
```

So, the routine isn't quit right on my system. I'm using the latest python
3 there is, but that might be my issue. It's suppose to have version 2
also, but I'm having difficulties with pip putting things in the right
place for each one.

**Comment by raguay** [comment]
I got python2 to work, but it still errors out:

```
Traceback (most recent call last):
  File "report.py", line 95, in <module>
    word_data_report(arg1, arg2)
  File "report.py", line 80, in word_data_report
    plt.title(str(dates[0])+' to '+str(dates[6]) + '\n Writing Typing Word Count: ' + str(dates_total))
IndexError: list index out of range
```
I'm guessing because I don't do much writing some days and it has no data, but isn't properly checking for the data to be there.

**Comment by markwk** [comment]
Cool. Thanks for giving it a try. Yes it's for Python 2 and you are probably right that we should set to zero if no data collected. Anyways, that's some feedback I can go forward with.
